# Generated by Django 2.0.2 on 2018-02-08 04:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('share_code', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField()),
                ('code', models.TextField()),
            ],
        ),
    ]
